version: '3.3'

services:
  edgeware:
    image: hicommonwealth/edgeware:v3.3.3
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:30333:30333"
    command:
      [
        '--dev',
        '--ws-external',
        '--port=30333',
        '--ws-port=9944',
        '--rpc-port=9933',
        '--wasm-execution=Compiled'
          # '--rpc-external',
          # '--rpc-cors',
          # '--chain=local',
          # '--validator',
      ]
